### ISSUE TITLE
Handle Game Completion

### ISSUE THREAD

**Issue by QuintonC** [drewradcliff/werdle#7]
When the game is complete we should show the user's current statistics and allow them to share their result to Twitter (auto-capture screenshot of the game board minus the letters), as well as copy an emoji board similar to how Wordle is currently doing it.

**Comment by drewradcliff** [comment]
screenshot of the game would essentially spoil the word of the day for others who haven't played that day

**Comment by QuintonC** [comment]
> screenshot of the game would essentially spoil the word of the day for others who haven't played that day

current idea implementation is to hide the keyboard as well as the letters during screenshot activity. (notice the animated implementation on the rows/keyboard already -- was planning ahead for that).

Devils advocate: We can't stop a user from screenshotting anyway. We're simply setting up a feature that would allow them to capture a screenshot with letters hidden by default and share directly to twitter.
